export type ProductPlan = {
  audience: "Өрхийн хэрэглэгч" | "Байгууллага";
  service: string;
  technology?: string;
  name: string;
  price: string;
  path: string;
  conditions: string[];
  note?: string;
};

export const VERIFIED_PRODUCT_PLANS: ProductPlan[] = [
  {
    audience: "Өрхийн хэрэглэгч",
    service: "Суурин утас",
    name: "Багц 1",
    price: "9,900₮",
    path: "/products/single",
    conditions: [
      "анхны холболт Улаанбаатарт 33,000₮, орон нутагт 16,500₮",
      "сүлжээндээ болон 26хххх дугаар руу хязгааргүй",
      "бусад сүлжээнд 100 минут",
      "нэмэлт үйлчилгээ 1ш",
    ],
  },
  {
    audience: "Өрхийн хэрэглэгч",
    service: "Суурин утас",
    name: "Багц 2",
    price: "16,500₮",
    path: "/products/single",
    conditions: [
      "анхны холболт Улаанбаатарт 33,000₮, орон нутагт 16,500₮",
      "сүлжээндээ болон 26хххх дугаар руу хязгааргүй",
      "бусад сүлжээнд 200 минут",
      "нэмэлт үйлчилгээ 3ш",
    ],
  },
  {
    audience: "Өрхийн хэрэглэгч",
    service: "Хосолсон багц",
    technology: "GPON",
    name: "S багц",
    price: "30,000₮",
    path: "/products/double",
    conditions: [
      "анхны холболт 16,500₮",
      "интернэтийн хурд 10Mbps",
      "сүлжээндээ болон 26хххх дугаар руу хязгааргүй",
      "бусад сүлжээнд 100 минут",
      "нэмэлт үйлчилгээ 1ш",
    ],
  },
  {
    audience: "Өрхийн хэрэглэгч",
    service: "Хосолсон багц",
    technology: "GPON",
    name: "M багц",
    price: "40,000₮",
    path: "/products/double",
    conditions: [
      "анхны холболт 16,500₮",
      "интернэтийн хурд 30Mbps",
      "сүлжээндээ болон 26хххх дугаар руу хязгааргүй",
      "бусад сүлжээнд 200 минут",
      "нэмэлт үйлчилгээ 3ш",
    ],
  },
  {
    audience: "Өрхийн хэрэглэгч",
    service: "Хосолсон багц",
    technology: "ADSL",
    name: "S багц",
    price: "19,800₮–24,200₮",
    path: "/products/double",
    conditions: [
      "анхны холболт Улаанбаатарт 22,000₮, орон нутагт 16,500₮",
      "интернэтийн хурд 2Mbps",
      "бусад сүлжээнд 100 минут",
      "нэмэлт үйлчилгээ 1ш",
    ],
  },
  {
    audience: "Өрхийн хэрэглэгч",
    service: "Хосолсон багц",
    technology: "ADSL",
    name: "M багц",
    price: "29,700₮–38,500₮",
    path: "/products/double",
    conditions: [
      "анхны холболт Улаанбаатарт 22,000₮, орон нутагт 16,500₮",
      "интернэтийн хурд 3Mbps",
      "бусад сүлжээнд 200 минут",
      "нэмэлт үйлчилгээ 3ш",
    ],
  },
  {
    audience: "Өрхийн хэрэглэгч",
    service: "Хосолсон багц",
    technology: "ADSL",
    name: "L багц",
    price: "39,600₮–49,500₮",
    path: "/products/double",
    conditions: [
      "анхны холболт Улаанбаатарт 22,000₮, орон нутагт 16,500₮",
      "интернэтийн хурд 5Mbps",
      "бусад сүлжээнд 200 минут",
      "нэмэлт үйлчилгээ 5ш",
    ],
  },
  {
    audience: "Өрхийн хэрэглэгч",
    service: "Гуравласан багц",
    name: "Багц 1",
    price: "49,500₮",
    path: "/products/triple",
    conditions: [
      "анхны холболт 22,000₮",
      "интернэтийн хурд 20Mbps",
      "бусад сүлжээнд 30 минут",
      "TV ROOM 80+ суваг",
      "PSN спорт болон 96 цаг нөхөж үзэх боломж",
      "нэмэлт үйлчилгээ 1ш",
    ],
  },
  {
    audience: "Өрхийн хэрэглэгч",
    service: "Гуравласан багц",
    name: "Багц 2",
    price: "66,000₮",
    path: "/products/triple",
    conditions: [
      "анхны холболт 22,000₮",
      "интернэтийн хурд 50Mbps",
      "бусад сүлжээнд 60 минут",
      "TV ROOM 80+ суваг",
      "PSN спорт болон 96 цаг нөхөж үзэх боломж",
      "нэмэлт үйлчилгээ 3ш",
    ],
  },
  {
    audience: "Өрхийн хэрэглэгч",
    service: "Гуравласан багц",
    name: "Сумын багц",
    price: "49,500₮",
    path: "/products/triple",
    conditions: [
      "анхны холболт 22,000₮",
      "интернэтийн хурд 10Mbps",
      "бусад сүлжээнд 30 минут",
      "TV ROOM 80+ суваг",
      "PSN спорт болон 96 цаг нөхөж үзэх боломж",
    ],
  },
  {
    audience: "Өрхийн хэрэглэгч",
    service: "Гуравласан багц",
    name: "Сумын алба хэрэглэгчийн багц",
    price: "165,000₮",
    path: "/products/triple",
    conditions: [
      "анхны холболт 22,000₮",
      "интернэтийн хурд 12Mbps",
      "бусад сүлжээнд 400 минут",
      "TV ROOM 80+ суваг",
      "PSN спорт болон 96 цаг нөхөж үзэх боломж",
    ],
  },
  {
    audience: "Өрхийн хэрэглэгч",
    service: "National КаТВ",
    name: "STANDARD багц",
    price: "12,000₮",
    path: "/products/catv",
    conditions: [
      "анхны холболт 5,500₮",
      "Монгол 59, спорт 10, хүүхдийн 5 суваг",
    ],
  },
  {
    audience: "Өрхийн хэрэглэгч",
    service: "National КаТВ",
    name: "PREMIUM багц",
    price: "14,000₮",
    path: "/products/catv",
    conditions: [
      "анхны холболт 5,500₮",
      "Монгол 59, спорт 10, хүүхдийн 5, танин мэдэхүйн 4, кино/интертэймент 8, мэдээний 7 суваг",
    ],
  },
  {
    audience: "Өрхийн хэрэглэгч",
    service: "TV ROOM",
    name: "STANDARD багц",
    price: "7,700₮",
    path: "/products/iptv",
    conditions: [
      "50–60 ТВ суваг",
      "PSN спортын 5 суваг болон 96 цаг нөхөж үзэх боломж дагалдахгүй",
      "зэрэг үзэх төхөөрөмж 1",
    ],
  },
  {
    audience: "Өрхийн хэрэглэгч",
    service: "TV ROOM",
    name: "PREMIUM багц",
    price: "13,200₮",
    path: "/products/iptv",
    conditions: [
      "80+ ТВ суваг",
      "PSN спортын 5 суваг болон 96 цаг нөхөж үзэх боломж дагалдана",
      "зэрэг үзэх төхөөрөмж 1",
    ],
  },
  {
    audience: "Өрхийн хэрэглэгч",
    service: "MIP70",
    name: "Багц 1",
    price: "7,700₮",
    path: "/products/sip",
    conditions: [
      "7008-**** дугаар",
      "анхны холболт 11,000₮",
      "30 хоногийн 5000 нэгж дагалдана",
      "бусад сүлжээнд 44₮",
      "дугаар солих болон эрх сэргээх тус бүр 3,300₮",
    ],
    note: "Хуудас дээр НӨАТ орсон гэж тэмдэглэсэн.",
  },
  {
    audience: "Байгууллага",
    service: "Суурин утас",
    name: "Багц 1",
    price: "16,500₮",
    path: "/products/corporate/single",
    conditions: [
      "анхны холболт Улаанбаатарт 33,000₮, орон нутагт 16,500₮",
      "бусад сүлжээнд 200 минут",
      "нэмэлт үйлчилгээ 1ш",
    ],
  },
  {
    audience: "Байгууллага",
    service: "Суурин утас",
    name: "Багц 2",
    price: "33,000₮",
    path: "/products/corporate/single",
    conditions: [
      "анхны холболт Улаанбаатарт 33,000₮, орон нутагт 16,500₮",
      "бусад сүлжээнд 400 минут",
      "нэмэлт үйлчилгээ 3ш",
    ],
  },
  {
    audience: "Байгууллага",
    service: "Суурин утас",
    name: "Багц 3",
    price: "49,500₮",
    path: "/products/corporate/single",
    conditions: [
      "анхны холболт Улаанбаатарт 33,000₮, орон нутагт 16,500₮",
      "бусад сүлжээнд 600 минут",
      "нэмэлт үйлчилгээ 5ш",
    ],
  },
  {
    audience: "Байгууллага",
    service: "Хосолсон багц",
    technology: "GPON",
    name: "S багц",
    price: "55,000₮",
    path: "/products/corporate/double",
    conditions: [
      "анхны холболт 16,500₮",
      "интернэтийн хурд 10Mbps",
      "бусад сүлжээнд 200 минут",
      "нэмэлт үйлчилгээ 5ш",
    ],
  },
  {
    audience: "Байгууллага",
    service: "Хосолсон багц",
    technology: "GPON",
    name: "M багц",
    price: "99,000₮",
    path: "/products/corporate/double",
    conditions: [
      "анхны холболт 16,500₮",
      "интернэтийн хурд 30Mbps",
      "бусад сүлжээнд 400 минут",
      "нэмэлт үйлчилгээ 7ш",
    ],
  },
  {
    audience: "Байгууллага",
    service: "Хосолсон багц",
    technology: "ADSL",
    name: "S багц",
    price: "42,900₮",
    path: "/products/corporate/double",
    conditions: [
      "анхны холболт 22,000₮",
      "интернэтийн хурд 3Mbps",
      "бусад сүлжээнд 200 минут",
      "нэмэлт үйлчилгээ 3ш",
    ],
  },
  {
    audience: "Байгууллага",
    service: "Хосолсон багц",
    technology: "ADSL",
    name: "M багц",
    price: "64,900₮",
    path: "/products/corporate/double",
    conditions: [
      "анхны холболт 22,000₮",
      "интернэтийн хурд 4Mbps",
      "бусад сүлжээнд 350 минут",
      "нэмэлт үйлчилгээ 5ш",
    ],
  },
  {
    audience: "Байгууллага",
    service: "Хосолсон багц",
    technology: "ADSL",
    name: "L багц",
    price: "86,900₮",
    path: "/products/corporate/double",
    conditions: [
      "анхны холболт 22,000₮",
      "интернэтийн хурд 5Mbps",
      "бусад сүлжээнд 500 минут",
      "нэмэлт үйлчилгээ 7ш",
    ],
  },
  {
    audience: "Байгууллага",
    service: "National КаТВ",
    name: "STANDARD багц",
    price: "12,000₮",
    path: "/products/corporate/catv",
    conditions: [
      "анхны холболт 5,500₮",
      "Монгол 42, хүүхдийн 1, кино/интертэймент 11 суваг",
    ],
  },
  {
    audience: "Байгууллага",
    service: "National КаТВ",
    name: "PREMIUM багц",
    price: "14,000₮",
    path: "/products/corporate/catv",
    conditions: [
      "анхны холболт 5,500₮",
      "Монгол 59, спорт 10, хүүхдийн 5, танин мэдэхүйн 4, кино/интертэймент 8, мэдээний 7 суваг",
    ],
  },
  {
    audience: "Байгууллага",
    service: "TV ROOM",
    name: "STANDARD багц",
    price: "7,700₮",
    path: "/products/corporate/iptv",
    conditions: [
      "50–60 ТВ суваг",
      "PSN спортын 5 суваг болон 96 цаг нөхөж үзэх боломж дагалдахгүй",
      "зэрэг үзэх төхөөрөмж 1",
    ],
  },
  {
    audience: "Байгууллага",
    service: "TV ROOM",
    name: "PREMIUM багц",
    price: "13,200₮",
    path: "/products/corporate/iptv",
    conditions: [
      "80+ ТВ суваг",
      "PSN спортын 5 суваг болон 96 цаг нөхөж үзэх боломж дагалдана",
      "зэрэг үзэх төхөөрөмж 1",
    ],
  },
  {
    audience: "Байгууллага",
    service: "Call Center",
    technology: "Физик кабель",
    name: "STANDARD багц",
    price: "55,000₮",
    path: "/products/corporate/callcenter",
    conditions: [
      "толгой дугаар",
      "ажлын цагийн тохиргоо",
      "автомат хариулагч",
      "дуудлага шилжүүлэх",
      "техникийн туслалцаа",
    ],
  },
  {
    audience: "Байгууллага",
    service: "Call Center",
    technology: "Физик кабель",
    name: "OPERATOR багц",
    price: "165,000₮",
    path: "/products/corporate/callcenter",
    conditions: [
      "STANDARD багцын боломжууд",
      "операторын ачаалал хуваарилах",
      "дуудлага бүлэглэх, түүх, тайлан",
      "IVR хоолой",
    ],
  },
  {
    audience: "Байгууллага",
    service: "Call Center",
    technology: "Шилэн кабель",
    name: "S багц",
    price: "55,000₮",
    path: "/products/corporate/callcenter",
    conditions: [
      "толгой дугаар",
      "ажлын цагийн тохиргоо",
      "автомат хариулагч",
      "дуудлага шилжүүлэх",
      "дотуур дугаар болон дуудлага хүлээлгэх тус бүр 2ш",
    ],
  },
  {
    audience: "Байгууллага",
    service: "Call Center",
    technology: "Шилэн кабель",
    name: "OPERATOR багц",
    price: "165,000₮",
    path: "/products/corporate/callcenter",
    conditions: [
      "дотуур дугаар болон дуудлага хүлээлгэх тус бүр 5ш",
      "дуудлага бүлэглэх, түүх, тайлан",
      "IVR хоолой бичүүлэх",
    ],
  },
  {
    audience: "Байгууллага",
    service: "Call Center",
    technology: "Шилэн кабель",
    name: "BUSINESS багц",
    price: "385,000₮",
    path: "/products/corporate/callcenter",
    conditions: [
      "нөхцөл зааж болон хариу өгөөгүй үед дуудлага шилжүүлэх",
      "хяналтын самбар, тайлан статистик",
      "дуудлагын түүх",
    ],
  },
];
